##
## EPITECH PROJECT, 2021
## Untitled (Workspace)
## File description:
## Makefile
##

.SILENT:

all:
	make -C Start

sfml:
	make -C Start

clean:
	make clean -C Start

fclean: clean
	make fclean -C Start

re:	fclean all


.PHONY: clean fclean re all 